name: Test

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: HelloWorld
        run: echo "Hello world"

      - name: List
        run: ls -all